# Generated by Django 5.2.1 on 2025-06-02 21:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_alter_visitor_session_key'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='event',
            options={'ordering': ['-timestamp'], 'verbose_name': 'Event', 'verbose_name_plural': 'Events'},
        ),
        migrations.AlterModelOptions(
            name='pageview',
            options={'ordering': ['-timestamp'], 'verbose_name': 'Page View', 'verbose_name_plural': 'Page Views'},
        ),
        migrations.AlterModelOptions(
            name='visitor',
            options={'ordering': ['-timestamp'], 'verbose_name': 'Visitor', 'verbose_name_plural': 'Visitors'},
        ),
        migrations.RemoveField(
            model_name='pageview',
            name='method',
        ),
        migrations.RemoveField(
            model_name='pageview',
            name='status_code',
        ),
        migrations.RemoveField(
            model_name='visitor',
            name='city',
        ),
        migrations.RemoveField(
            model_name='visitor',
            name='is_bot',
        ),
        migrations.RemoveField(
            model_name='visitor',
            name='is_mobile',
        ),
        migrations.RemoveField(
            model_name='visitor',
            name='is_pc',
        ),
        migrations.RemoveField(
            model_name='visitor',
            name='is_tablet',
        ),
        migrations.RemoveField(
            model_name='visitor',
            name='session_key',
        ),
        migrations.RemoveField(
            model_name='visitor',
            name='user',
        ),
        migrations.AddField(
            model_name='event',
            name='category',
            field=models.CharField(choices=[('engagement', 'Engagement'), ('navigation', 'Navigation'), ('conversion', 'Conversion')], default='engagement', max_length=20),
        ),
        migrations.AddField(
            model_name='event',
            name='page_url',
            field=models.URLField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='event',
            name='element_class',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='element_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='event_type',
            field=models.CharField(choices=[('pageview', 'Page View'), ('click', 'Click'), ('download', 'File Download'), ('form_submit', 'Form Submission'), ('external_link', 'External Link'), ('scroll', 'Page Scroll'), ('video_play', 'Video Play')], max_length=20),
        ),
        migrations.AlterField(
            model_name='event',
            name='visitor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='dashboard.visitor'),
        ),
        migrations.AddIndex(
            model_name='event',
            index=models.Index(fields=['event_type'], name='dashboard_e_event_t_6352d9_idx'),
        ),
        migrations.AddIndex(
            model_name='event',
            index=models.Index(fields=['timestamp'], name='dashboard_e_timesta_e1a955_idx'),
        ),
    ]
