# Generated by Django 5.2.1 on 2025-06-02 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_alter_event_options_alter_pageview_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='visitor',
            name='session_key',
            field=models.CharField(default=1, max_length=40, unique=True),
            preserve_default=False,
        ),
    ]
