# Generated by Django 5.2.1 on 2025-06-02 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_visitor_session_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visitor',
            name='session_key',
            field=models.CharField(max_length=40),
        ),
    ]
