# Generated by Django 5.2.1 on 2025-06-04 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0006_remove_event_category_alter_event_event_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='visitor',
            name='last_seen',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
